### ISSUE TITLE
Skipper on macOS: permission issue 

### ISSUE THREAD

**Issue by nmagnezi** [Stratoscale/skipper#136]
How to reproduce (on macOS):
- Project: [assited-service](https://github.com/openshift/assisted-service)
- Skiper conf: this [skipper.yaml](https://github.com/openshift/assisted-service/blob/9feb42c785968109e5df62a2bba5295bbcc77a6e/skipper.yaml) with the[ libvirt specific lines ](https://github.com/openshift/assisted-service/blob/9feb42c785968109e5df62a2bba5295bbcc77a6e/skipper.yaml#L12-L13) removed (worked well in the past)

`skipper make generate-from-swagger`

The error I get:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/opt/skipper/skipper-entrypoint.sh\": permission denied": unknown.
`

The full log:
```
[skipper] No build container tag was provided
[skipper] Building image using docker file: Dockerfile.assisted-service-build
Sending build context to Docker daemon  210.8MB
Step 1/8 : FROM quay.io/app-sre/golang:1.14.3
 ---> 7e5e8028e8ec
Step 2/8 : ENV GO111MODULE=on
 ---> Using cache
 ---> 4c4fd3cb9a1a
Step 3/8 : RUN apt-get update && apt-get install -y docker.io libvirt-clients awscli python3-pip postgresql  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> fb401dce6731
Step 4/8 : RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
 ---> Using cache
 ---> 3c380c14f0a3
Step 5/8 : RUN go get -u github.com/onsi/ginkgo/ginkgo@v1.12.2               golang.org/x/tools/cmd/goimports@v0.0.0-20200520220537-cf2d1e09c845               github.com/golang/mock/mockgen@v1.4.3               github.com/vektra/mockery/.../@v1.1.2               gotest.tools/gotestsum@v0.5.3               github.com/axw/gocov/gocov               github.com/AlekSi/gocov-xml@v0.0.0-20190121064608-3a14fb1c4737
 ---> Using cache
 ---> 8ef85f123b4e
Step 6/8 : RUN pip3 install boto3==1.13.14 waiting==1.4.1 requests==2.22.0 mkdocs==1.1.2
 ---> Using cache
 ---> 14dd80b7d245
Step 7/8 : RUN curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.10.1/minikube-linux-amd64   && chmod +x minikube && mkdir -p /usr/local/bin/ && install minikube /usr/local/bin/
 ---> Using cache
 ---> dbe92f2d1c6a
Step 8/8 : RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
 ---> Using cache
 ---> 27734d8c463a
Successfully built 27734d8c463a
Successfully tagged assisted-service-build:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/opt/skipper/skipper-entrypoint.sh\": permission denied": unknown.
```

**Comment by michaellevy101** [comment]
please share your skipper lib directory in the docker desktop preferences 
For example, for me is to add the location:
/usr/local/lib/python3.9/site-packages/skipper
to the prefernces->Resources->FILE SHARING
 
 The Skipper maps the entrypoint file as a volume:
  -v /usr/local/lib/python3.9/site-packages/skipper/data/skipper-entrypoint.sh:/opt/skipper/skipper-entrypoint.sh 
  If docker has no permission for this directory it won't be able to access this file and it created an empty folder instead of mapping the actual file

**Comment by romfreiman** [comment]
Or use Fedora
