### ISSUE TITLE
PR #168 broke current configurations

### ISSUE THREAD

**Issue by rccrdpccl** [Stratoscale/skipper#173]
Projects using the following config are not working after [this PR](https://github.com/Stratoscale/skipper/pull/168)

```yaml
volumes:
  - $HOME/.docker/:$HOME/.docker
```
Can we please find a way to work around this? Maybe not adding again this mount point if already explicitly declared?
@khizunov @ofir-amir

**Comment by khizunov** [comment]
@rccrdpccl thanks, fixing it
