### ISSUE TITLE
Add target image tag to skipper.yml

### ISSUE THREAD

**Issue by shay-stratoscale** [Stratoscale/skipper#45]
I want to be able to define a tag with a different name from the docker file, 
please add an optional option to skipper.yml to set the target image tag.

@adir-stratoscale

**Comment by adir-stratoscale** [comment]
Fixed by 9457c73d43fff916ae68aa4e6fe0206f60e06aa5.

**Comment by adir-stratoscale** [comment]
duplicates #59.
