### ISSUE TITLE
skipper is messing up commands arguments 

### ISSUE THREAD

**Issue by shay-stratoscale** [Stratoscale/skipper#79]
for example

```
-installsuffix 
```

is translated to
```
-nstallsuffx 
```

@adir-stratoscale @eran-stratoscale

**Comment by adir-stratoscale** [comment]
@shay-stratoscale 
the problem with your example is that skipper interprets `-i` as a parameter to the `run` command. 
you can instruct skipper to stop interpreting parameters by providing them after the `--` delimiter. 
for example: 
`skipper run ls -- --help`

**Comment by shay-stratoscale** [comment]
@adir-stratoscale the parameter is written in a command inside a Makefile, and I used `skipper make` to run it.

can you offer a solution for that case?

**Comment by adir-stratoscale** [comment]
@shay-stratoscale can you give here an elaborated example for the case?

**Comment by shay-stratoscale** [comment]
make file example 

```
...

make build:
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o build/main -ldflags "-X lib/version.revisionHash=84ecffe" cmd/credit-manager-server/main.go

...
```

running `skipper make build` will fails because of the bug I've described

**Comment by shay-stratoscale** [comment]
@adir-stratoscale are you going to address this issue?

**Comment by eran-stratoscale** [comment]
Failed to reproduce 
makefile:
`ls:
	ls -il
`
running `skipper make ls`
works fine.

**Comment by shay-stratoscale** [comment]
fixed somehow,,,
